defaults:
  - default.yaml
  - model: audio_codec
  - _self_


# Add audio encoder lr
optimizer:
  lr_audio: 1e-3

data:
  window_seconds: 30
  grid_ms: 20

loader:
  augment: false

seed: 42

tracking:
  tags: [audio]
